version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    networks:
      - app-network
    env_file:
      - ./auth-service/.env

  todo-service:
    build: ./todo-service
    ports:
      - "3002:3002"
    networks:
      - app-network
    env_file:
      - ./todo-service/.env

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
