name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push Docker images for each service
    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push

    # Optional Step 5: Run tests (if you have any tests defined)
    - name: Run tests
      run: |
        # For example, if you're using Jest or Mocha for tests:
        # npm install
        # npm test
        echo "Running tests"
